use Pokemon;

select name from Trainer where hometown = 'Blue City';
select name from Trainer where hometown = 'Brown City' or hometown = 'Rainbow City';
select name, hometown from Trainer where name regexp '^[aeiou]';
select name from Pokemon where type = 'Water';
select distinct type from Pokemon;
select name from Pokemon order by name;
select name from Pokemon where name like '%s';
select name from Pokemon where name like '%e%s';
select name from Pokemon where name regexp '^[aeiou]';
select type, count(type) as number from Pokemon group by type;
select nickname from CatchedPokemon order by level desc limit 3;
select avg(level) as AVG_lev from CatchedPokemon;
select max(level) - min(level) as gap from CatchedPokemon;
select count(name) as number from Pokemon where 'f' > name >'b';
select count(type) as number from Pokemon where  type != 'Fire' &&  type != 'Grass' && type != 'Water' && type != 'Electric';
select T.name as Trainer_name, nickname, P.name as Pokemon_name from Trainer as T, CatchedPokemon as C, Pokemon as P where owner_id = T.id and pid = P.id and nickname like '% %';
select T.name from Trainer as T, CatchedPokemon as C, Pokemon as P where T.id = C.owner_id and C.pid = P.id and P.type = 'Psychic';
select T.name, T.hometown from Trainer as T, CatchedPokemon as C where T.id = owner_id group by owner_id order by avg(level) desc limit 3;
select T.name, count(owner_id) as number from Trainer as T, CatchedPokemon as C where T.id = owner_id group by owner_id order by count(owner_id) desc, T.name desc;
select P.name, C.level from Pokemon as P, CatchedPokemon as C, Trainer as T, Gym as G where G.city = 'sangnok City' and G.leader_id = T.id and C.owner_id = T.id and C.pid = P.id order by (C.level);
select P.name, count(C.pid) as catched_number from Pokemon as P left join CatchedPokemon as C on P.id = C.pid group by P.id order by count(C.pid) desc;
select P.name from Pokemon as P where P.id IN (select E.after_id from Evolution as E where E.before_id IN (select E.after_id from Pokemon as P, Evolution as E where E.before_id = P.id and P.name = 'Charmander'));
select P.name from Pokemon as P, CatchedPokemon as C where P.id = C.pid and P.id <= 30 group by C.pid order by P.name;
select T.name, P.type from Trainer as T, Pokemon as P, CatchedPokemon as C where T.id = C.owner_id and C.pid = P.id group by C.owner_id having count(distinct P.type) = 1;
select T.name, P.type, count(P.type) as number from Trainer as T, Pokemon as P, CatchedPokemon as C where T.id = C.owner_id and C.pid = P.id group by C.owner_id, P.type;
select T.name, P.name, count(C.owner_id) as catched_number from Trainer as T, Pokemon as P, CatchedPokemon as C where T.id = C.owner_id and C.pid = P.id group by C.owner_id having count(distinct C.pid) = 1;
select T.name, City.name as city_name from Trainer as T, Pokemon as P, CatchedPokemon as C, Gym as G, City where G.leader_id = T.id and G.city = City.name and T.id = C.owner_id and C.pid = P.id group by C.owner_id having count(distinct P.type) > 1;
select T.name, sum(if(C.level>=50, C.level, null)) as SUM_lev from Trainer as T, CatchedPokemon as C, Gym as G, City where G.leader_id = T.id and G.city = City.name and T.id = C.owner_id group by C.owner_id;
select P.name from Trainer as T, Pokemon as P, CatchedPokemon as C where T.id = C.owner_id and C.pid = P.id and T.hometown in('Sangnok city', 'Blue City')  group by C.pid having count(distinct T.hometown) > 1;
select P.name from Pokemon as P where P.id in (select after_id from Evolution) and P.id not in(select before_id from Evolution);
